import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <div className="flex h-screen overflow-hidden">
    <Sidebar/>
      <main className="w-full pt-4">{children}</main>
    </div>
  </>
  );
}
